using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

// THE BUG THIS EXISTS FOR: a robot that drives at a goal ends up INSIDE it and cannot back out.
//
// A goal's collision is not its mesh — FieldSetupTools generates it as flat BoxCollider panels laid on
// the edges of an octagon (the outer bumper ring), a second octagon (the lower base rim), a hexagon (the
// inner pocket the pieces stack in) and a floor. Two things about the two RING shells made a goal a trap:
//
//   1. THE CORNERS WERE OPEN. Eight flat panels on an octagon's edges do not meet at the vertices unless
//      each panel is wider than its edge. Measured on the shipped field, every ring on every one of the
//      nine goals had a ~0.125-unit gap at all eight corners, running the ring's full height: eight
//      slots a thin robot part slides straight through.
//   2. THE PANELS WERE 0.01 UNITS THICK. That is 1 mm at this project's scale — at or below the physics
//      contact offset, and a fraction of what a driving robot covers in one 100 Hz step. A collider that
//      does end up overlapping one has its nearest exit face half a millimetre away on EITHER side, so
//      depenetration is a coin flip and it can just as easily be pushed further in.
//
// Together: the frame slips in through a corner slot and then has nothing solid to be pushed back out
// by. It reads as "the bot gets stuck inside the goal", and it shows up on a robot whose aligner/bumper
// is RETRACTED, because an extended one holds the frame off the goal and it never reaches the shell.
//
// The fix is entirely in the collider sizes: thicken the ring panels so depenetration has a direction,
// and widen them so neighbours cross at the corners and the ring closes. Nothing visible changes — these
// colliders have no renderer; the goal you SEE is the MeshInstance children next to them.
//
// FieldSetupTools now generates goals this way. This tool retro-fits the goals already saved in the
// scenes, so nobody has to re-run the interactive goal builder and re-enter its tuned radii. Idempotent:
// panel thickness is the marker, so a wall that is already at spec is left alone and re-running is a
// no-op (which also means a goal regenerated by FieldSetupTools is correctly skipped).
//
// The INNER POCKET is deliberately untouched: its six panels already meet, nothing but game pieces ever
// touches them, and thickening them would eat into the pocket whose clearances the stack heights are
// tuned against.
//
// Usage: Tools > RoboSim > Field & Pieces > Seal Goal Shells (Scene Fix).
// Batch: -executeMethod SealGoalShell.RunBatch.
public static class SealGoalShell
{
    [MenuItem("Tools/RoboSim/Field & Pieces/Seal Goal Shells (Scene Fix)", false, 5)]
    private static void SealInteractive()
    {
        if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo()) return;

        string previousScenePath = SceneManager.GetActiveScene().path;
        string report = SealAllScenes();
        if (!string.IsNullOrEmpty(previousScenePath))
            EditorSceneManager.OpenScene(previousScenePath, OpenSceneMode.Single);

        Debug.Log("Seal Goal Shells: " + report);
        EditorUtility.DisplayDialog("Seal Goal Shells", report, "OK");
    }

    public static void RunBatch()
    {
        Debug.Log("Seal Goal Shells: " + SealAllScenes());
    }

    private static string SealAllScenes()
    {
        var lines = new List<string>();
        foreach (string scenePath in new[] { RoboSimPaths.MainScene, RoboSimPaths.LiteScene })
        {
            if (!System.IO.File.Exists(scenePath)) { lines.Add($"{scenePath}: not found, skipped."); continue; }

            Scene scene = EditorSceneManager.OpenScene(scenePath, OpenSceneMode.Single);
            int sealedPanels = SealOpenScene(scene, out int alreadyOk, out int skipped);
            if (sealedPanels > 0) EditorSceneManager.SaveScene(scene);
            lines.Add($"{System.IO.Path.GetFileName(scenePath)}: {sealedPanels} ring panels sealed, " +
                      $"{alreadyOk} already at spec{(skipped > 0 ? $", {skipped} SKIPPED (see warnings)" : "")}.");
        }
        return string.Join("  ", lines);
    }

    // Walks the open scene and brings every ring panel up to spec. Returns how many were changed;
    // `alreadyOk` counts the ones that were already sealed (so re-running reports honestly rather than
    // claiming to have done work) and `skipped` counts panels whose shape isn't what the generator
    // writes — those get a warning instead of a silent guess at which axis is the thickness.
    //
    // Public so the validator can seal a throwaway fixture and prove this method is what closes it.
    public static int SealOpenScene(Scene scene, out int alreadyOk, out int skipped)
    {
        int changed = 0;
        alreadyOk = 0;
        skipped = 0;

        foreach (GameObject root in scene.GetRootGameObjects())
        {
            foreach (Transform t in root.GetComponentsInChildren<Transform>(true))
            {
                if (!GoalShellSpec.IsRingWall(t.name)) continue;
                BoxCollider box = t.GetComponent<BoxCollider>();
                if (box == null) continue;

                Vector3 size = box.size;

                // The generator writes (width, thickness, height) — thickness on Y, and by a long way the
                // smallest axis. Anything else is a hand-edited or renamed collider, and widening the
                // wrong axis of one would push a wall through the goal it belongs to.
                if (size.y > size.x || size.y > size.z)
                {
                    Debug.LogWarning($"Seal Goal Shells: '{t.name}' has size {size} — its thinnest axis " +
                                     "isn't Y, which is the only shape the goal generator produces. " +
                                     "Left alone; check this collider by hand.", t);
                    skipped++;
                    continue;
                }

                if (size.y >= GoalShellSpec.RingThickness - GoalShellSpec.Epsilon) { alreadyOk++; continue; }

                Undo.RecordObject(box, "Seal Goal Shell");
                box.size = new Vector3(size.x + GoalShellSpec.CornerOverlap, GoalShellSpec.RingThickness, size.z);
                EditorUtility.SetDirty(box);
                changed++;
            }
        }
        return changed;
    }
}

// The numbers the goal's collision shell is built to, in one place: the generator (FieldSetupTools), the
// retro-fit above and GoalShellValidation all read them, so "what a sealed goal is" can't drift between
// the thing that builds it, the thing that repairs it and the thing that checks it.
internal static class GoalShellSpec
{
    // Ring-panel thickness (world units; 1 unit is 10 cm here, so this is a 1 cm wall). Ten times the
    // old 0.01 and ten times the project's contact offset, which is what gives PhysX a definite side to
    // push a penetrating robot part back out of.
    public const float RingThickness = 0.1f;

    // Added to each ring panel's WIDTH so neighbouring panels overlap at the octagon's corners instead of
    // leaving a slot. The shipped goals' corner gaps measure ~0.125 units and close at +0.15; +0.2 keeps
    // margin for goals regenerated at other radii. It only spreads panels along the ring, so the goal's
    // footprint is unchanged apart from a little extra material buried in each corner.
    public const float CornerOverlap = 0.2f;

    // The inner pocket keeps the original thin panels — see the header for why.
    public const float PocketThickness = 0.01f;

    public const float Epsilon = 1e-4f;

    // The two shells a ROBOT can hit. The inner pocket is not one of them.
    public static bool IsRingWall(string objectName) =>
        objectName.StartsWith("GoalWall_Outer_Octagon") || objectName.StartsWith("GoalWall_Lower_Base_Octagon");
}
